idpscraper/urls.py
""" This file links the views to their urls """
__author__ = 'Sebastian Hofstetter'

from django.urls import path
from . import views

app_name = 'idpscraper'
urlpatterns = [
    path('', views.index, name='index'),
    path('task/<name>', views.task, name='task'),
    path('console', views.console, name='console'),
    path('export_task/<name>.txt', views.export_task, name='export_task'),
    path('save_task/<name>', views.save_task, name='save_task'),
    path('delete_task/<name>', views.delete_task, name='delete_task'),
    path('export_excel/<name>.xlsx', views.export_excel, name='export_excel'),
    path('run_task/<name>', views.run_task, name='run_task'),
    path('run_command', views.run_command, name='run_command'),
    path('new_task', views.new_task, name='new_task'),
    path('delete_results/<name>', views.delete_results, name='delete_results'),
    path('test_task/<name>', views.test_task, name='test_task'),
    path('get_task_selectors/<name>', views.get_task_selectors, name='get_task'),

    path('apartment_settings', views.apartment_settings, name='apartment_settings'),
    path('save_apartment_settings', views.save_apartment_settings, name='save_apartment_settings'),
    path('run_apartment_settings', views.run_apartment_settings, name='run_apartment_settings'),
]

idpscraper/models/apartment_settings.py
""" Apartment Settings """
__author__ = 'Sebastian Hofstetter'

from django.db import models


class ApartmentSettings(models.Model):
    """Apartment Settings """
    id = models.TextField(primary_key=True, default="global", editable=False)
    email_to = models.TextField()
    email_from = models.TextField()
    password = models.TextField()
    smtp_server = models.TextField()
    smtp_port = models.IntegerField(default=465)
    fetch_intervall = models.IntegerField(default=60)
    last_update = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def get():
        """ Fetch global Apartment Settings """
        if not ApartmentSettings.objects.all():
            ApartmentSettings().save()
        return ApartmentSettings.objects.get(pk="global")

idpscraper/models/task.py
""" General model for a webscraping task """
__author__ = 'Sebastian Hofstetter'

import itertools
from idpscraper.models import UrlSelector, Selector, Result
from django.db import models
import logging
from lxml import html, etree  # xpath support
from requests import Session  # for login required http requests
import re
import time
import traceback
import datetime


class Task(models.Model):
    """ A Webscraper Task """

    name = models.TextField(primary_key=True)

    @property
    def recursive_url_selectors(self):
        """ Returns all url_selectors that contain a reference to the own task """
        return [url_selector for url_selector in self.url_selectors.all() if url_selector.has_dynamic_url and url_selector.selector_task_id == self.pk]

    def __str__(self):
        return self.name

    def __repr__(self):
        fields = ["name"]
        fields = ", ".join(["%s=%s" % (f, repr(getattr(self, f))) for f in fields])
        return "Task(%s)" % fields

    def get_urls(self, results=None, limit=None):
        """ Return all (possibly dynamic) urls related to the task """
        return itertools.chain(*[url_selector.get_urls(results=results, limit=limit) for url_selector in self.url_selectors.all()])  # Keep generators intact!

    @staticmethod
    def get(name):
        """ Fetch a task by name """
        return Task.objects.get(pk=name)

    def as_table(self, results):
        """ Prepare a set of results in a table like format, where the first row states the columns' titles """
        yield tuple(selector.name for selector in self.selectors.all())

        for result in results:
            yield tuple(getattr(result, selector.name) if hasattr(result, selector.name) else None for selector in self.selectors.all())

    def run(self, limit=None, store=True) -> 'list[Result]':
        """ Execute a task """
        urls = set(self.get_urls(limit=limit))
        visited_urls = set()
        all_results = []

        while len(urls) > 0:
            logging.info("Remaining: %s" % len(urls))
            url = urls.pop()
            if url not in visited_urls:
                visited_urls.add(url)

                # Fetch Result #
                results = self.http_request(url)
                all_results += results

                if store and results:
                    # Store result in database #
                    for result in results:
                        result.save()

                    # Schedule new urls on recursive call #
                    if self.recursive_url_selectors:
                        urls.update(self.recursive_url_selectors[0].get_urls(results=results))

        return all_results

    def test(self):
        """ Execute a task without storing the results in the database """
        return self.run(limit=1, store=False)

    def export(self):
        """ Return the python representation of the task """
        return ",\n".join([repr(m) for m in [self] + list(self.selectors.all()) + list(self.url_selectors.all())])

    def export_to_excel(self):
        """ Return the binary excel data of the task's results """
        return Task.export_data_to_excel(data=self.as_table(self.results.all()))

    @staticmethod
    def export_data_to_excel(data):
        """ Return the binary excel data of the given data """
        import xlsxwriter  # Excel export support
        import io  # for files in memory

        output = io.BytesIO()
        w = xlsxwriter.Workbook(output, dict(in_memory=True))
        ws = w.add_worksheet("data")
        ws.set_column('A:Z', 25)  # set more appriate width

        cell_types = {
            repr(type(None)): w.add_format(),
            repr(datetime.datetime): w.add_format(dict(num_format="DD.MM.YYYY")),
            repr(int): w.add_format(dict(num_format="0")),
            repr(float): w.add_format(dict(num_format="0.00")),
            repr(str): w.add_format(dict(num_format="@")),
        }

        # write #
        for x, row in enumerate(data):
            for y, column in enumerate(row):
                ws.write(x, y, column, cell_types[repr(type(column))])

        # save #
        w.close()
        output.seek(0)
        return output.read()

    def parse(self, html_src: str) -> 'list[Result]':
        """ Parses an html document for a given XPath expression. Any resulting node can optionally be filtered against a regular expression """

        # In the following some xpath extension functions are introduced. They can be used in the xpath fields of a task's selectors #
        def textify(node):
            return (str(node.text) if hasattr(node, "text") else str(node)).strip()

        def merge_lists(context, *args):
            """ Merge the items of lists at same positions. If one list is shorter, its last element is repeated """
            try:
                return [" ".join([textify(arg[min(i, len(arg) - 1)]) for arg in args]) for i in range(max(map(len, args)))]
            except Exception as e:
                return [""]

        def exe(context, nodes, path):
            """ Executes a given xpath with each node in the first xpath as context node """
            try:
                return [textify(node.xpath(path).pop()) if node.xpath(path) else "" for node in nodes]
            except Exception as e:
                return [""]

        def all(context, nodes):
            return [" ".join(textify(node) for node in nodes)]

        ns = etree.FunctionNamespace(None)
        ns['merge_lists'] = merge_lists
        ns['exe'] = exe
        ns['all'] = all

        if not self.selectors.all():
            return html_src  # nothing to do

        parsed_tree = html.document_fromstring(html_src)

        selectors_results = []
        for selector in self.selectors.all():
            nodes = parsed_tree.xpath(selector.xpath)
            nodes = [textify(node) for node in nodes]

            if selector.regex:
                # Apply regex to every single node #
                selector_results = []
                for node in nodes:
                    node = str(node)
                    regex_result = re.search(selector.regex, node, re.DOTALL | re.UNICODE)
                    if regex_result:
                        if regex_result.groups():
                            selector_results += [regex_result.groups()[-1]]
                        else:
                            selector_results += [regex_result.group()]
                    else:
                        selector_results += [None]
            else:
                selector_results = nodes

            selector_results = [selector.cast(data) if data is not None else None for data in selector_results]  # cast to type

            selectors_results.append(selector_results)

        # convert selector results from a tuple of lists to a list of tuples #
        results = []
        for y in range(max([len(selectors_results[list(self.selectors.all()).index(key_selector)]) for key_selector in self.selectors.all() if key_selector.is_key])):  # Take as many results, as there are results for a key selector
            result = Result(task_id=self.name)
            for x, selector in enumerate(self.selectors.all()):
                selectors_results[x] = selectors_results[x] or [None]  # Guarantee that an element is there
                setattr(result, selector.name, selectors_results[x][min(y, len(selectors_results[x]) - 1)])

            result.key = result.get_key()
            if result.key:
                results.append(result)

        return results

    def login(self, url: str, user: str, password: str) -> Session:
        """ Returns the session that is yielded by the login """

        session = Session()
        inputs = self.http_request(url, session=session)
        inputs[0].value = user  # TODO: more intelligent search for correct user and password field in form. Currently just the first two input fields are taken.
        inputs[1].value = password
        data = {input.name: input.value for input in inputs}
        session.post(url, data)
        return session

    def http_request(self, url: str, session: Session=None) -> 'list[Result]':
        """ Returns the response of an http get-request to a given url """
        success = False

        while not success:
            try:
                logging.info("Requested %s" % url)  # For Debugging purposes
                session = session or Session()
                html_src = session.get(url, timeout=120).text
                parsing = self.parse(html_src)
                success = True
                time.sleep(0.3)  # Do not DOS the server!
            except Exception as e:
                traceback.print_exc()
                time.sleep(5)

        return parsing

idpscraper/templates/idpscraper/apartment_settings.html
{% extends "idpscraper/layout.html" %}

{% block title %}Apartment Settings{% endblock %}
{% block h1 %}Apartment Settings{% endblock %}

{% block content %}
    <form id="apartment_settings_form">
        <h4>Receiver Email</h4>
        <input type="text" name="email_to" value="{{ apartment_settings.email_to }}" placeholder='To' class="input_long">

        <h4>Email Credentails (for automatic email notifications)</h4>
        <input type="text" name="email_from" value="{{ apartment_settings.email_from }}" placeholder='From' class="input_long">
        <input type="password" name="password" value="{{ apartment_settings.password }}" placeholder='Password' class="input_short">

        <h4>SMTP Server</h4>
        <input type="text" name="smtp_server" value="{{ apartment_settings.smtp_server }}" placeholder='Host' class="input_short">
        <input type="text" name="smtp_port" value="{{ apartment_settings.smtp_port }}" placeholder='Port' class="input_short">

        <h4>Fetch Intervall (seconds)</h4>
        <input type="text" name="fetch_intervall" value="{{ apartment_settings.fetch_intervall }}" placeholder='Fetch Intervall' class="input_short">

        <br>
        Last WebScraper Update: {{ apartment_settings.last_update }}
        <br>

        <!--<h2>Scam Filters</h2>-->

        <br>
        <button type="button" class="btn" onclick="save_apartment_settings(function() {window.location.reload();})">Save</button>
        <button type="button" class="btn" onclick="run_apartment_settings()">Run</button>
    </form>
{% endblock %}

idpscraper/templates/idpscraper/console.html
{% extends "idpscraper/layout.html" %}

{% block title %}Console{% endblock %}
{% block h1 %}Console{% endblock %}

{% block content %}
<input type="text" id="command" class="input_long" value='len(Task.get("Football_Matches").results.all())'><br>

<button class="btn" onclick="console_eval($('#command').val())">Eval</button>
{% endblock %}

idpscraper/templates/idpscraper/index.html
{% extends "idpscraper/layout.html" %}

{% block title %}All Tasks{% endblock %}
{% block h1 %}All Tasks{% endblock %}

{% block content %}
<ul>
    {% for task in tasks %}
        <li><a href="{% url 'idpscraper:task' task.name %}">{{ task.name }}</a></li>
    {% endfor %}
</ul>

<button class="btn" onclick="new_task()">Create New Task</button>
{% endblock %}

idpscraper/templates/idpscraper/layout.html
{% load staticfiles %}
{% load idpscraper_extras %}

<!DOCTYPE html>

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <script src="{% static 'idpscraper/js/jquery.js' %}"></script>
    <script src="{% static 'idpscraper/js/modernizr.custom.js' %}"></script>
    <script src="{% static 'idpscraper/js/com.js' %}"></script>
    <script src="{% static 'idpscraper/js/FileSaver.js' %}"></script>
    <script src="{% static 'idpscraper/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'idpscraper/js/web2py.js' %}"></script>
    <script src="{% static 'idpscraper/js/web2py_bootstrap.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'idpscraper/css/web2py.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'idpscraper/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'idpscraper/css/bootstrap-responsive.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'idpscraper/css/web2py_bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'idpscraper/css/com.css' %}"/>
</head>


<body>
<div class="navbar navbar-inverse">

    <!-- Flash Message -->
    <div class="flash">
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% endif %}
    </div>

    <!-- Navbar -->
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="{% url 'idpscraper:index' %}"><b>IDP<span>Scraper</span></b>©&nbsp;</a>

            <div class="nav">
                <ul class="nav">
                    <!--<li class="web2py-menu-first"><a href="{% url 'admin:index' %}">Administration</a></li>-->
                    <li class="web2py-menu-last"><a href="{% url 'idpscraper:apartment_settings' %}">Apartment Settings</a></li>
                    <!--<li class="web2py-menu-last"><a href="{% url 'idpscraper:console' %}">Console</a></li>-->
                </ul>
            </div>
        </div>
    </div>

</div>


<div class="container">

    <!-- Title Header -->
    <header class="mastheader row" id="header">
        <div class="span12">
            <div class="page-header">
                <h1>
                    {% block h1 %}{% endblock %}
                </h1>
            </div>
        </div>
    </header>

    <!-- Main -->
    <section id="main" class="main row">
        <div class="span12">
            {% block content %}{% endblock %}
        </div>
    </section>

    <!-- Footer -->
    <div class="row">
        <footer class="footer span12" id="footer">
            <div class="footer-content">
                {% block footer %}
                    <div class="copyright pull-left">Copyright &#169; {% now "Y" %}</div>
                    <div id="poweredBy" class="pull-right">
                        <a href="https://linkedin.com/in/sebastian-hofstetter-772b6192">Sebastian Hofstetter</a>
                    </div>
                {% endblock %}
            </div>
        </footer>
    </div>

</div>

{% csrf_token %}
</body>
</html>

idpscraper/templates/idpscraper/task.html
{% extends "idpscraper/layout.html" %}

{% block title %}{{ task.name }}{% endblock %}
{% block h1 %}{{ task.name }}{% endblock %}

{% block content %}
    <!-- Properties -->
    <form id="task_form">
        <div>
            <h3>URLs</h3>

            <div id="url_selectors">
                {% for url_selector in task.url_selectors.all %}
                    <div class="url_selector">
                        <input type="text" name="url[]" placeholder="http://..." value="{{ url_selector.url }}" class="input_long">
                    <span class="advanced">
                        <select name="url_results_id[]" class="results_id" onchange="update_results_properties({{ forloop.counter0 }})">
                            {% for task in all_tasks %}
                                <option {% if task.pk == url_selector.selector_task_id %} selected {% endif %}>{{ task.name }}</option>
                            {% endfor %}
                        </select>
                        <select name="url_selector_name[]" class="results_properties1" style="width: 150px">
                            {% for selector in url_selector.selector_task.selectors.all %}
                                <option {% if selector.name == url_selector.selector_name %} selected {% endif %}>{{ selector.name }}</option>
                            {% endfor %}
                        </select>
                        <select name="url_selector_name2[]" class="results_properties2" style="width: 150px">
                            {% for selector in url_selector.selector_task.selectors.all %}
                                <option {% if selector.name == url_selector.selector_name2 %} selected {% endif %}>{{ selector.name }}</option>
                            {% endfor %}
                        </select>
                    </span>
                    </div>
                {% endfor %}
            </div>

            <button type="button" class="btn" onclick="remove_url_selector()">-</button>
            <button type="button" class="btn" onclick="add_url_selector()">+</button>
        </div>

        <div>
            <h3>Content</h3>

            <div id="content_selectors">
                {% for selector in task.selectors.all %}
                    <div class="content_selector">
                        <input type="checkbox" {% if selector.is_key %}checked{% endif %} name="selector_is_key" value="{{ forloop.counter0 }}"> Key &nbsp;&nbsp;
                        <input type="text" name="selector_name[]" value="{{ selector.name }}" placeholder='Player Height' class="input_short">
                        <input type="text" name="selector_xpath[]" value="{{ selector.xpath }}" placeholder='//div[class="player_height"]//text()' class="input_long">
                    <span class="advanced">
                        <select name="selector_type[]">
                            {% for selector_choice in selector_choices %}
                                <option {% if forloop.counter0 == selector.type %} selected {% endif %} value="{{ forloop.counter0 }}">{{ selector_choice.1 }}</option>
                            {% endfor %}
                        </select>
                        <input type="text" name="selector_regex[]" value="{{ selector.regex }}" placeholder='RegEx (optional)' class="input_short">
                    </span>
                    </div>
                {% endfor %}
            </div>

            <button type="button" class="btn" onclick="remove_content_selector()">-</button>
            <button type="button" class="btn" onclick="add_content_selector()">+</button>
        </div>
        {% csrf_token %}
    </form>

    <!-- Options -->
    <button class="btn" onclick="save('{{ task.name }}', function() {window.location.reload()})">Save</button>
    <button class="btn btn-success" onclick="test('{{ task.name }}')">Test</button>
    <button class="btn btn-success" onclick="run('{{ task.name }}')">Run</button>
    <button class="btn btn-danger advanced" onclick="delete_task('{{ task.name }}')">Delete</button>
    <button class="btn btn-danger advanced" onclick="delete_results('{{ task.name }}')">Delete Results</button>
    <button class="btn" onclick="export_excel('{{ task.name }}')">Export to Excel</button>
    <button class="btn advanced" onclick='window.location ="{% url 'idpscraper:export_task' task.name %}"'>Export Task</button>
    <button class="btn" id="swap_advanced" onclick="swap_advanced()">Advanced View</button>

    <table class="com_default_table">
        {% for row in data %}
            <tr>
                {% for cell in row %}
                    <td>
                        {{ cell }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>

    <script>
        $(apply_advanced);
    </script>
{% endblock %}